version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER} # should be postgres - other roles are not defined
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 1s
      timeout: 1s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    depends_on:
      - postgres
    ports:
      - "1071:1071"
    volumes:
      - ./backend:/backend/
    restart: "on-failure"
    environment:
      - DB_HOST=${DB_HOST}
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      
  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    depends_on:
      - postgres
    volumes:
     - type: bind
       source: ./frontend
       target: /app
     - /app/node_modules
    ports:
      - "8080:8080"
    environment:
     - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata: