version: '3.8'

services:

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    volumes:
     - type: bind
       source: ./frontend
       target: /app
    ports:
      - "8080:8080"
    environment:
     - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    ports:
      - "1071:1071"
    volumes:
      - ./backend:/backend/
    restart: "on-failure"